"""Initial migration1.

Revision ID: a4a1ec85cf1d
Revises: 2f6a1f7636f7
Create Date: 2022-02-10 15:41:49.349831

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a4a1ec85cf1d'
down_revision = '2f6a1f7636f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'user_type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('user_type', sa.VARCHAR(length=20), nullable=False))
    # ### end Alembic commands ###
